if vim.g.loaded_wayfinder then
  return
end

vim.g.loaded_wayfinder = 1

local wayfinder = require("wayfinder")

wayfinder.setup()

vim.keymap.set("n", "<Plug>(WayfinderOpen)", function()
  wayfinder.open()
end, { silent = true, desc = "Open Wayfinder" })
vim.keymap.set("n", "<Plug>(WayfinderTrailNext)", function()
  wayfinder.trail_next()
end, { silent = true, desc = "Next Wayfinder Trail item" })
vim.keymap.set("n", "<Plug>(WayfinderTrailPrev)", function()
  wayfinder.trail_prev()
end, { silent = true, desc = "Previous Wayfinder Trail item" })
vim.keymap.set("n", "<Plug>(WayfinderTrailOpen)", function()
  wayfinder.trail_open()
end, { silent = true, desc = "Open current Wayfinder Trail item" })
vim.keymap.set("n", "<Plug>(WayfinderTrailShow)", function()
  wayfinder.trail_show()
end, { silent = true, desc = "Open Wayfinder on Trail" })

vim.api.nvim_create_user_command("Wayfinder", function()
  wayfinder.open()
end, { desc = "Open Wayfinder for the current symbol or file" })
vim.api.nvim_create_user_command("WayfinderExportQuickfix", function()
  wayfinder.export_quickfix()
end, { desc = "Export the current Wayfinder facet to quickfix" })
vim.api.nvim_create_user_command("WayfinderExportTrailQuickfix", function()
  wayfinder.export_trail_quickfix()
end, { desc = "Export Wayfinder Trail to quickfix" })
vim.api.nvim_create_user_command("WayfinderTrailNext", function()
  wayfinder.trail_next()
end, { desc = "Open the next Wayfinder Trail item" })
vim.api.nvim_create_user_command("WayfinderTrailPrev", function()
  wayfinder.trail_prev()
end, { desc = "Open the previous Wayfinder Trail item" })
vim.api.nvim_create_user_command("WayfinderTrailOpen", function()
  wayfinder.trail_open()
end, { desc = "Open the current Wayfinder Trail item" })
vim.api.nvim_create_user_command("WayfinderTrailShow", function()
  wayfinder.trail_show()
end, { desc = "Open Wayfinder on the Trail facet" })
vim.api.nvim_create_user_command("WayfinderTrailSave", function()
  wayfinder.trail_save()
end, { desc = "Save the current Wayfinder Trail" })
vim.api.nvim_create_user_command("WayfinderTrailSaveAs", function()
  wayfinder.trail_save_as()
end, { desc = "Save the current Wayfinder Trail with a new name" })
vim.api.nvim_create_user_command("WayfinderTrailLoad", function()
  wayfinder.trail_load()
end, { desc = "Load a saved Wayfinder Trail" })
vim.api.nvim_create_user_command("WayfinderTrailResume", function()
  wayfinder.trail_resume()
end, { desc = "Resume the last active saved Wayfinder Trail" })
vim.api.nvim_create_user_command("WayfinderTrailDelete", function()
  wayfinder.trail_delete()
end, { desc = "Delete a saved Wayfinder Trail" })
vim.api.nvim_create_user_command("WayfinderTrailRename", function()
  wayfinder.trail_rename()
end, { desc = "Rename a saved Wayfinder Trail" })
